# Generated by Django 5.2 on 2025-06-09 13:17

from django.db import migrations

def create_default_categories(apps, schema_editor):
    Category = apps.get_model('book', 'Category')
    default_categories = [
        'Önfejlesztés',
        'Motiváció',
        'Pszichológia',
        'Romantikus',
        'Fantasy',
    ]
    
    for name in default_categories:
        Category.objects.get_or_create(name = name)

class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]
