# Generated by Django 5.2 on 2025-06-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_add_default_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='fee',
        ),
    ]
