# Generated by Django 5.2 on 2025-06-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='borrow',
            name='debt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='BorrowFee',
        ),
    ]
